apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-05-21T01:41:59Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "741"
  uid: 35944f06-e253-4dd5-90e0-cf160c72a242
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.121.252
  clusterIPs:
  - 10.96.121.252
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31830
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
